#
# meatplatform-sandbox
# Distributed under CC BY-NC-SA
#
server:
  port: ${SANDBOXAPP_SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: meatplatform-sandbox-server
  profiles:
    # local, alpha, beta, release, test
    active: ${SANDBOXAPP_SERVER_PROFILE:local}
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:/sql/schema/*.sql
      # data-locations: classpath:/sql/data/*.sql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${SANDBOXAPP_SERVER_MARIADB_HOST}:${SANDBOXAPP_SERVER_MARIADB_PORT}/${SANDBOXAPP_SERVER_MARIADB_DB}?serverTimezone=UTC&useUnicode=true&character_set_server=utf8mb4;
    username: ${SANDBOXAPP_SERVER_MARIADB_USERNAME}
    password: ${SANDBOXAPP_SERVER_MARIADB_PASSWORD}

# Spring Boot Actuator 는 서버내의 민감한 정보를 노출하기 때문에, 별도의 port 로 운영합니다.
# 접근이 손쉬운 HTTP 로는 기능을 최대한 숨기고, JMX 를 이용한 기능만 활성화하는 편이 좋습니다.
#
# 하지만 이 예제에서는 SANDBOXAPP_MANAGE_PORT 의 ACL 을 별도로 설정했다고 가정하고, Shutdown 을 제외한
# Actuator 모든 의 기능을 엽니다.
#
# 참고 문서: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator
management:
  # Web port
  server:
    port: ${SANDBOXAPP_MANAGE_PORT:8284}
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info
        exclude: *
    # JMX port 설정은 https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.jmx 를 참고하세요.
    jmx:
      exposure:
        include: *
        exclude: shutdown

sandboxapp:
  authentication:
    rsaCert:
      cacheCapacity: ${SANDBOXAPP_SERVER_RSA_KEY_CACHE_SIZE:100}
      keySize: ${SANDBOXAPP_SERVER_RSA_KEY_SIZE:2048}
      keyActiveSeconds: ${SANDBOXAPP_SERVER_RSA_KEY_ACTIVE_SECONDS:86400}
    token:
      issuer: "net.meatplatform.sandbox"
      accessTokenLifeSeconds: ${SANDBOXAPP_SERVER_ACCESS_TOKEN_LIFE_SECONDS:7200}
      refreshTokenLifeSeconds: ${SANDBOXAPP_SERVER_REFRESH_TOKEN_LIFE_SECONDS:15552000}

  client:
    minVersion: "1.0.0"
    defaultWebUrl: "https://github.dev/sirloin-dev/meatplatform-sandbox"
    updateUri:
      android: "https://github.dev/sirloin-dev/meatplatform-sandbox"
      ios: "https://github.dev/sirloin-dev/meatplatform-sandbox"
      web: "https://github.dev/sirloin-dev/meatplatform-sandbox"
      windows: "https://github.dev/sirloin-dev/meatplatform-sandbox"
      linux: "https://github.dev/sirloin-dev/meatplatform-sandbox"
      macos: "https://github.dev/sirloin-dev/meatplatform-sandbox"

  thirdparty:
    google:
      oAuthUrl: https://accounts.google.com/o/oauth2/v2/auth
    apple:
      oAuthUrl: https://appleid.apple.com/auth/keys
